# change to false to stop auto-update-check
auto_update_check: true
# set to true before sending a log about an issue.
#logs trace data required to pinpoint where errors are.
debug: false
# en_US, nl_NL, fr_FR, de_DE, zh_CN, cs-CZ, pt_BR
lang: en_US

# Following are chance percent settings for each mob and variants of mobs.
# Hieronder volgen instellingen voor het toevalspercentage voor elke mob en varianten van mobs.
# Voici les paramètres de pourcentage de chance pour chaque mob et les variantes de mobs.
# Es folgen die Einstellungen für die Wahrscheinlichkeit in Prozent für jeden Mob und Varianten von Mobs.
# 以下是每个生物和生物变种的机会百分比设置。
# Následuje nastavení procenta šancí pro každý mob a varianty mobs.
# A seguir, estão as configurações de porcentagem de chance para cada mob e variantes de mobs.
# 0.001 = 1/10 of 1 percent, 0.01 = 1 percent, 1.00 = 100 percent
named_mob_chance_percent: 0.10
bat_chance_percent: 0.025
blaze_chance_percent: 0.025
cat:
  black_cat_chance_percent: 0.025
  red_cat_chance_percent: 0.025
  siamese_cat_chance_percent: 0.025
  wild_ocelot_chance_percent: 0.025
cave_spider_chance_percent: 0.025
chicken_chance_percent: 0.025
cod_chance_percent: 0.025
cow_chance_percent: 0.025
creeper_chance_percent: 0.025
dolphin_chance_percent: 0.025
donkey_chance_percent: 0.025
drowned_chance_percent: 0.025
elder_guardian_chance_percent: 0.025
ender_dragon_chance_percent: 0.025
enderman_chance_percent: 0.025
endermite_chance_percent: 0.025
evoker_chance_percent: 0.025
fox_chance_percent: 0.025
ghast_chance_percent: 0.025
giant_chance_percent: 0.025
guardian_chance_percent: 0.01
horse:
  black_chance_percent: 0.025
  brown_chance_percent: 0.025
  chestnut_chance_percent: 0.025
  creamy_chance_percent: 0.025
  dark_brown_chance_percent: 0.025
  gray_chance_percent: 0.025
  white_chance_percent: 0.025
husk_chance_percent: 0.025
illusioner_chance_percent: 0.025
iron_golem_chance_percent: 0.025
llama:
  brown_chance_percent: 0.025
  creamy_chance_percent: 0.025
  gray_chance_percent: 0.025
  white_chance_percent: 0.025
magma_cube_chance_percent: 0.025
mule_chance_percent: 0.025
mushroom_cow:
  brown_chance_percent: 0.025
  red_chance_percent: 0.025
parrot:
  blue_chance_percent: 0.025
  cyan_chance_percent: 0.025
  gray_chance_percent: 0.025
  green_chance_percent: 0.025
  red_chance_percent: 0.025
phantom_chance_percent: 0.025
pig_chance_percent: 0.025
pillager_chance_percent: 0.025
polar_bear_chance_percent: 0.025
pufferfish_chance_percent: 0.025
rabbit:
  black_chance_percent: 0.025
  black_and_white_chance_percent: 0.025
  brown_chance_percent: 0.025
  gold_chance_percent: 0.025
  salt_and_pepper_chance_percent: 0.025
  the_killer_bunny_chance_percent: 0.025
  toast_chance_percent: 0.025
  white_chance_percent: 0.025
ravager_chance_percent: 0.025
salmon_chance_percent: 0.025
sheep:
  black_chance_percent: 0.025
  blue_chance_percent: 0.025
  brown_chance_percent: 0.025
  cyan_chance_percent: 0.025
  gray_chance_percent: 0.025
  green_chance_percent: 0.025
  jeb__chance_percent: 0.025
  light_blue_chance_percent: 0.025
  light_gray_chance_percent: 0.025
  lime_chance_percent: 0.025
  magenta_chance_percent: 0.025
  orange_chance_percent: 0.025
  pink_chance_percent: 0.025
  purple_chance_percent: 0.025
  red_chance_percent: 0.025
  white_chance_percent: 0.025
  yellow_chance_percent: 0.025
shulker_chance_percent: 0.025
silverfish_chance_percent: 0.025
skeleton_chance_percent: 0.025
skeleton_horse_chance_percent: 0.025
slime_chance_percent: 0.025
snowman_chance_percent: 0.025
spider_chance_percent: 0.025
squid_chance_percent: 0.025
stray_chance_percent: 0.025
#########################################
tropical_fish_chance_percent: 0.025
turtle_chance_percent: 0.025
vex_chance_percent: 0.025
villager:
  black_smith_chance_percent: 0.025
  butcher_chance_percent: 0.025
  farmer_chance_percent: 0.025
  librarian_chance_percent: 0.025
  nitwit_chance_percent: 0.025
  normal_chance_percent: 0.025
  priest_chance_percent: 0.025
vindicator_chance_percent: 0.025
wandering_trader_chance_percent: 0.025
witch_chance_percent: 0.025
wither_chance_percent: 0.025
wither_skeleton_chance_percent: 0.025
wolf_chance_percent: 0.025
zombie_chance_percent: 0.025
zombie_horse_chance_percent: 0.025
zombie_pigman_chance_percent: 0.025
zombie_villager_chance_percent: 0.025