# DO NOT CHANGE VERSION
version: 1.0.30
plugin_settings:
  auto_update_check: true
  debug: false
  lang: en_US
global_settings:
  console:
    colorful_console: true
    silent_console: false
    longpluginname: true
  world:
    whitelist:
    blacklist:
  event:
    piston_extend: true
head_settings:
  apply_looting: true
  lore:
    show_killer: true
    show_plugin_name: true
  mini_blocks:
    stonecutter: true
    perblock: 1
  player_heads:
    announce_kill:
      enabled: true
      displayname: true
    whitelist:
      enforce: false
      player_head_whitelist: names_go_here
    blacklist:
      enforce: false
      player_head_blacklist: names_go_here
    use_default_player_heads: true
  mob_heads:
    announce_kill:
      enabled: true
      displayname: true
    whitelist:
    blacklist:
    nametag: false
    vanilla_heads:
      creeper: false
      ender_dragon: false
      piglin: false
      skeleton: false
      wither_skeleton: false
      zombie: false
wandering_trades:
  custom_wandering_trader: true
  keep_default_trades: true
  player_heads:
    enabled: true
    min: 0
    max: 3
  block_heads:
    enabled: true
    min: 1
    max: 5
  custom_trades:
    enabled: false
    min: 0
    max: 5