name: MoreMobHeads
main: com.github.joelgodofwar.mmh.MoreMobHeads
version: 1.14_1.0.14a
author: JoelYahwehOfWar
api-version: 1.13

commands:
  mmh:
    description: Shows MoreMobHeads help.
    usage: /<command>

permissions:
  moremobheads.players:
    description: Allows the player to get player head drops from killing players.
    default: true
  moremobheads.mobs:
    description: Allows the player to get mob head drops from killing mobs.
    default: true
  moremobheads.nametag:
    description: Allows the player to name a mob(Skeleton/Zombie/ZombiePigman/Villagers) using a nametag to get a playerhead.
    default: op
  moremobheads.reload:
    description: Allows the player to use "/mmh reload" command.
    default: op
  moremobheads.toggledebug:
    description: Allows the player to use "/mmh toggledebug" command.
    default: op
  moremobheads.showUpdateAvailable:
    description: Shows player that there is a version update.
    default: op
  moremobheads.customtrader:
    description: Allows player to use custom trader commands.
    default: op
  moremobheads.playerheads:
    description: Allows player to use player heads commands.
    default: op
  moremobheads.blockheads:
    description: Allows player to use block heads commands.
    default: op