name: MoreMobHeads
main: com.github.joelgodofwar.mmh.MoreMobHeads
version: 1.14_1.0.0
author: JoelYahwehOfWar
api-version: 1.13

permissions:
  moremobheads.players:
    description: Allows the player to get player head drops from killing players.
    default: true
  moremobheads.mobs:
    description: Allows the player to get mob head drops from killing mobs.
    default: true
  moremobheads.nametag:
    description: Allows the player to name a mob(Skeleton/Zombie/ZombiePigman) using a nametag to get a playerhead.
    default: true
